### ISSUE TITLE
is it possible to handle telnet over the PPP ip

### ISSUE THREAD

**Issue by badgroot** [openvehicles/Open-Vehicle-Monitoring-System-3#286]

**Comment by dexterbg** [comment]
That isn't really an issue. Please post questions on the user forum at www.openvehicles.com.

To answer this: yes.
But the telnet console is by default disabled because it's inherently insecure. Use ssh.
Generally, the module listens on all interfaces. There is currently no firewall. So both the ssh and the http server of the module can be used via GSM.

All you need is a SIM provider / plan that supports IP routing to the device.
The included Hologram SIM can provide IP routing by the Hologram Spacebridge service:
https://hologram.io/docs/guide/connect/protocols/#spacebridge-ip-tunnel
Other SIM providers may enable routing by default or may generally not support this. Ask them.

To get your current GSM IP, check `network status`.
