### ISSUE TITLE
Update Copyright date values to year 2024 on https://www.openvehicles.com/ and https://docs.openvehicles.com/

### ISSUE THREAD

**Issue by fowi4hjte** [openvehicles/Open-Vehicle-Monitoring-System-3#990]
On https://www.openvehicles.com/ at the bottom of the page is written "Copyright (c) 2011-2022 Open Vehicles Limited"
On https://docs.openvehicles.com/ at the bottom of the page is written "© Copyright 2019-2020, Open Vehicles Developers"

Both should have year 2024 instead of 2022 or 2020.

But also this wakes up a question on my side. The main page is copyright to the company. The doc is copyright to the developers. Why the difference? Maybe change both to developers instead of Limited to represent more the community?
And more general: I expect the copyright that should be working is the copyright on the name of the product. Like Firefox where own builds that get released are not allowed to be named Firefox but should be named different like icefox or other examples. Am i right with my expectation?

**Comment by markwj** [comment]
> On https://www.openvehicles.com/ at the bottom of the page is written "Copyright (c) 2011-2022 Open Vehicles Limited"
> On https://docs.openvehicles.com/ at the bottom of the page is written "© Copyright 2019-2020, Open Vehicles Developers"
> Both should have year 2024 instead of 2022 or 2020.

The copyright date should cover the years that the work was created/changed. So, for the product website, the statement is correct (as the website text hasn't had any substantial changes since released in 2022). For the docs.openvehicles.com site, we have updated it to be 2019-2024 to reflect the new documentation.

> The main page is copyright to the company. The doc is copyright to the developers. Why the difference? 

Because the main page was authored by the company (or employees of the company), and the documentation (and code) was authored by the developers.

> I expect the copyright that should be working is the copyright on the name of the product.

Copyright concerns the rights of an author/creator, and as such involves a 'person' (either natural or organisational). A 'product' cannot be the author/creator of a copyrighted work (although the recent advances in AI may prove troublesome in this respect). Neither can you assign copyright to a product. The closest would be 'Open Vehicles Ltd'.

In an ideal world, it would be good to have the copyright clearly in the name of one 'person', but that is simply not possible. Even if we were to demand that all the 100+ direct contributors to OVMS assign their copyright to one 'person', we would still have all the individual copyrights in all the individual third party libraries we use.

You mention Firefox as an example. In that case the current source code for Firefox contains over 57,000 individual copyright statements, of which a rough count shows 3,110 as unique. The top contributor is 'Ecma International' (copyright 2012), then 'the Sputnik authors' (copyright 2009), then a general unicode copyright, then a brave 'Any copyright is dedicated to the Public Domain' in fourth place. The words 'Mozilla' or 'Firefox' only appear 14 times in that list of 57,000+ copyright statements. I think you get the idea.

> Like Firefox where own builds that get released are not allowed to be named Firefox but should be named different like icefox or other examples

I think here you are contributing copyright with trademark. The mark 'Firefox' is trademarked by Mozilla Foundation, and protected as such in specific classes and countries. For example, the mark 'FIREFOX' is registered in Hong Kong to Mozilla Foundation under class 9 (Mobile phones; handheld mobile digital electronic devices for the sending and receiving of telephone calls, electronic mail, and other digital data, for use as a digital format audio player, and for use as a handheld computer, personal digital assistant, electronic organizer, electronic notepad, and camera; operating system software; software for use in developing, executing, and running other software on mobile communication devices, computers, computer networks, and global communication networks; graphical user interface software; application development tool software; software for accessing, organizing, and managing multiple software applications, sold as an integral component of computer operating system and graphical user interface software).

The names 'OVMS' or 'Open Vehicle Monitoring System' are not currently trademarked. The expense of that (estimated as USD100,000 in the markets we operate in, with perhaps another USD10,000 /year to maintain them, assuming no major objections) is just infeasible for a project such as ours. We are, however, protected by 'prior use'. Should someone try to trademark our name, we could object on the grounds that we've been using it since 2011.

I hope that answers your questions, and addresses your concerns.

I will mark this as closed, as the change to the docs website has already been released.
