### ISSUE TITLE
Make the text of the documentation and main website licenced under CC-BY-SA-4.0

### ISSUE THREAD

**Issue by fowi4hjte** [openvehicles/Open-Vehicle-Monitoring-System-3#991]
Currently there is no proper license for the text written on the OVMS websites. This is in general not a good choice without having to go deep into licensing and legal things. The Free Software Foundation is a good source to learn more about licenses of text when combined with software code. For example the story how they realized after few years why their GNU FDL was not a good idea compared to CC-BY-SA-4.0 is a nice learning topic if interested into licenses.

The shortest conclusion is: Just write on the bottom of the pages "Content on this site is licensed under CC-BY-SA-4.0 license".
Wikipedia can be taken as a example for such a license.

And the general legal text for such topics: This is just my opinion. I am not a layer.

**Comment by markwj** [comment]
Wikipedia is like it is because the site is primarily (99.99...%) content generated by the users, and they want some control over the redistribution of that (ie; protection against blanket copying of wikipedia to some other straight copy without restriction). They require the copy to give credit (attribution) to the original.

I do note that we have forums on our site, and there may be 'ownership' issues related to that content - but it is clearly a public forum and anything posted their clearly published publicly. The individual authors of that content would retain their own copyright (although maybe hard to enforce given the nature of the release).

It would be extremely rare for the static text or images on a website to be ever licensed. The function of al license  is to outline the terms under which something may be legally copied to be used elsewhere, but why would someone want to copy the www.openvehicles.com website? Wikipedia goes to great lengths to try to ensure everything submitted to their site is provided with that same license. We don't have that luxury (for example, a large number of stock artwork not licensed under CC-BY-SA-4.0).

The static text  on the product website was authored by, and is copyright, Open Vehicles Ltd, and should not be used elsewhere without permission. It would simply be too complex to do otherwise, imho.
